package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	wd, err := os.Getwd()
	if err != nil {
		log.Fatalf("Failed to get working directory: %v", err)
	}

	modulesDir, err := resolveModulesDir(wd)
	if err != nil {
		log.Fatalf("Failed to resolve modules directory: %v", err)
	}

	packages := discoverModulePackages(modulesDir)
	sort.Strings(packages)

	if err := generateLoader(modulesDir, packages); err != nil {
		log.Fatalf("Failed to generate loader: %v", err)
	}

	log.Println("Successfully generated loader.go")
}

func resolveModulesDir(wd string) (string, error) {
	cleanWd := filepath.Clean(wd)
	if filepath.Base(cleanWd) == "loader" {
		return filepath.Clean(filepath.Join(cleanWd, "..")), nil
	}

	if filepath.Base(cleanWd) == "modules" {
		return cleanWd, nil
	}

	candidate := filepath.Join(cleanWd, "pkg", "modules")
	if info, err := os.Stat(candidate); err == nil && info.IsDir() {
		return candidate, nil
	}

	return "", fmt.Errorf("unable to locate pkg/modules from %s", wd)
}

// discoverModulePackages scans for subdirectories containing Go files with
// init() functions that call plugin.Register
func discoverModulePackages(root string) []string {
	var packages []string

	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if !entry.IsDir() {
			return nil
		}

		dirName := entry.Name()
		if dirName == "loader" || strings.HasPrefix(dirName, ".") {
			return filepath.SkipDir
		}

		if path == root {
			return nil
		}

		if hasModuleRegistration(path) {
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			packages = append(packages, filepath.ToSlash(rel))
		}

		return nil
	})

	if err != nil {
		log.Fatalf("Failed to scan modules: %v", err)
	}

	return packages
}

// hasModuleRegistration checks if a directory contains an init() function
// that calls plugin.Register
func hasModuleRegistration(dir string) bool {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool { //nolint:staticcheck // TODO: migrate to golang.org/x/tools/go/packages
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)

	if err != nil {
		return false
	}

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			if hasRegistrationInit(file) {
				return true
			}
		}
	}

	return false
}

// hasRegistrationInit checks if a file has an init() that registers modules
func hasRegistrationInit(file *ast.File) bool {
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Name.Name != "init" {
			continue
		}

		if fn.Body != nil {
			for _, stmt := range fn.Body.List {
				if hasRegistrationCall(stmt) {
					return true
				}
			}
		}
	}
	return false
}

// hasRegistrationCall checks if a statement contains plugin.Register
func hasRegistrationCall(stmt ast.Stmt) bool {
	exprStmt, ok := stmt.(*ast.ExprStmt)
	if !ok {
		return false
	}

	call, ok := exprStmt.X.(*ast.CallExpr)
	if !ok {
		return false
	}

	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}

	ident, ok := sel.X.(*ast.Ident)
	if !ok {
		return false
	}

	return ident.Name == "plugin" && sel.Sel.Name == "Register"
}

// generateLoader creates the loader.go file with all imports
func generateLoader(modulesDir string, packages []string) error {
	loaderDir := filepath.Join(modulesDir, "loader")
	if err := os.MkdirAll(loaderDir, 0o755); err != nil {
		return fmt.Errorf("failed to create loader directory: %w", err)
	}

	loaderPath := filepath.Join(loaderDir, "loader.go")
	file, err := os.Create(loaderPath)
	if err != nil {
		return fmt.Errorf("failed to create loader file: %w", err)
	}
	defer func() { _ = file.Close() }()

	// Write file header
	_, _ = fmt.Fprintf(file, "// Code generated by tools/modules/generator.go. DO NOT EDIT.\n")
	_, _ = fmt.Fprintln(file, "// This file is automatically generated during build")
	_, _ = fmt.Fprintln(file, "// To regenerate, run: go generate ./pkg/modules/loader")
	_, _ = fmt.Fprintln(file)
	_, _ = fmt.Fprintln(file, "package loader")
	_, _ = fmt.Fprintln(file)
	_, _ = fmt.Fprintln(file, "import (")

	for _, pkg := range packages {
		importPath := fmt.Sprintf("github.com/praetorian-inc/aurelian/pkg/modules/%s", pkg)
		_, _ = fmt.Fprintf(file, "\t_ %q\n", importPath)
	}

	_, _ = fmt.Fprintln(file, ")")

	return nil
}
