// Code generated by tools/modules/generator.go. DO NOT EDIT.
// This file is automatically generated during build
// To regenerate, run: go generate ./pkg/modules/loader

package loader

import (
	_ "github.com/praetorian-inc/aurelian/pkg/modules/aws/analyze"
	_ "github.com/praetorian-inc/aurelian/pkg/modules/aws/recon"
	_ "github.com/praetorian-inc/aurelian/pkg/modules/azure/recon"
)
